targets:
  $default:
    sources:
      include:
        - lib/**.f.dart # freezed
        - lib/**.r.dart # auto_route
        - lib/**.b.dart # built_value
        - test/**.m.dart # mockito
        - $package$
        - lib/$lib$
