name: sanctions_checker
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  built_value: ^8.6.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed: ^2.4.5
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  intl: any
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  sliver_tools: ^0.2.12
  ui_kit:
    path: packages/ui_kit

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  built_value_generator: ^8.6.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  
  uses-material-design: true

  assets:
    - assets/parsed_documents/
